propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native

  artista:
    nombre: { primaryString: true}
    
  ciudad:
    nomCiudad: { primaryString: true}
    
  privilegios:
    descripcion: { primaryString: true}