propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native

  artista:
    nombre: { primaryString: true}
    
  ciudad:
    nomCiudad: { primaryString: true}
    
  privilegios:
<<<<<<< HEAD
    descripcion: { primaryString: true}
    
  genero:
    tipo: { primaryString: true }
    
  proveedor:
    nombre: { primaryString: true }
=======
    descripcion: { primaryString: true}
>>>>>>> 68100c847fe003581072155b095140633b522771
